name: news
description: A Flutter news app demonstrating Clean Architecture and SOLID principles.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Network
  http: ^1.1.0
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # JSON Serialization (annotations only - for runtime)
  json_annotation: ^4.8.1
  
  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  
  # URL Launcher
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48